#!/bin/bash
# Can be used to make a dummy B2 repo for testing, e.g.
# rclone lsl --b2-versions B2:mybucket | b2restore-create-dummy-files -d outdir
# M.Blakeney, May 2018.

usage() {
    echo "Usage: $(basename $0) [-options]"
    echo "Reads B2 file list (from lsl output) from standard input to create"
    echo "dummy tree of files."
    echo "Options:"
    echo "-d <outdir> default = current dir"
    echo "-z (zero fill files, not with random content which is default)"
    echo "-s (set files to zero length, not their actual size)"
    exit 1
}

OUTDIR=""
NOSIZE=0
ZERO=""
while getopts d:zs c; do
    case $c in
    d) OUTDIR=$OPTARG;;
    z) ZERO="-z";;
    s) NOSIZE=1;;
    \?) usage;;
    esac
done

shift $((OPTIND - 1))

if [[ $# -ne 0 ]]; then
    usage
fi

if [[ -n $OUTDIR ]]; then
    OUTDIR=$OUTDIR/
fi

while read size date time file; do
    mkdir -p "$OUTDIR""$(dirname $file)"
    if [[ $NOSIZE -eq 0 ]]; then
	echo "creating ($size bytes):" "$OUTDIR""$file"
	fallocate $ZERO -l $size "$OUTDIR""$file"
    else
	echo creating: "$OUTDIR""$file"
    fi
    touch -d "${date}T${time}" "$OUTDIR""$file"
done
